---
- hosts: all
  become: true
  remote_user: root
  gather_facts: yes
  vars_files:
    - default_vars.yml
  roles:
    - role: common
    - role: user
    - role: postgres
    - role: gantsign.oh-my-zsh
      users:
        - username: deploy
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
              - vi-mode
              - git-extras
              - common-aliases
    - role: rbenv
    - role: ufw
    - role: nginx
    - role: geerlingguy.nodejs
    - role: lockdown
